# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    displayName: Sum of two numbers
    jobs:
      - job:
        displayName: steps.bash
        steps:
          - bash: |
              which bash
              Sum=$(($a+$b))
              echo $Sum>sum_with_bash.txt
            displayName: 'Compute Sum'
            env:
              a: 6
              b: 9
          
          - publish: fisier.txt
            displayName: Publish artifact
      
      - job:
        displayName: steps.powershell
        steps:
          - powershell: | 
              ($a+$b)>sum_with_powershell.txt
            env:
              a: 6
              b: 9