# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:            
  - stage:
    displayName: Sum of two numbers
    jobs:
      - job:
        displayName: steps.bash
        steps:
          - bash: |
              which bash
              Sum=$(($a+$b))  
            displayName: 'Compute Sum'
            env:
              a: 6
              b: 9
            
          - script: |
              echo $Sum
            displayName: 'Display Sum'
          
          - script:
              echo $Sum>fisier.txt
            displayName: 'Write sum to file'
          
          - publish: fisier.txt
            displayName: Publish artifact       